from __future__ import annotations


PROJECT_URL = "https://msab-patent-landscape.onrender.com"
PROJECT_NAME = "MsAb-PatKG Report Generator"
PDF_WATERMARK_TEXT = f"{PROJECT_NAME} | {PROJECT_URL}"
SOURCE_NOTE = (
    f"Generated by the {PROJECT_NAME}. Project URL: {PROJECT_URL}. "
    "Website development and operation supported by Haomai."
)
